class ClientRoles:
    READ_LOGS_ROLE = "read:logs"
    READ_USERS_ROLE = "read:users"
    READ_ADMIN_ROLE = "read:admin"
    READ_MAP_ROLE = "read:map"
    READ_ASSETS_ROLE = "read:assets"
    READ_RULES_ROLE = "read:rules"
    READ_INSIGHTS_ROLE = "read:insights"
    READ_ALARMS_ROLE = "read:alarms"
    READ_SERVICES_ROLE = "read:services"
    WRITE_SERVICES_ROLE = "write:services"
    WRITE_USER_ROLE = "write:user"
    WRITE_ADMIN_ROLE = "write:admin"
    WRITE_LOGS_ROLE = "write:logs"
    WRITE_ASSETS_ROLE = "write:assets"
    WRITE_ATTRIBUTES_ROLE = "write:attributes"
    WRITE_RULES_ROLE = "write:rules"
