[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = true
message = "chore: bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

