version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s %(levelname)s [%(name)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  default:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  "":
    level: DEBUG
    handlers:
      - default
    propagate: false
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: false
  uvicorn.access:
    level: INFO
    handlers:
      - default
    propagate: false 