// Copyright 2025, OpenRemote Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// TODO: Automatically generate the Models via OpenAPI spec -- See https://github.com/openremote/service-ml-forecast/issues/31

/**
 * Enum representing the different types of models available.
 * Corresponds to service_ml_forecast.models.model_type.ModelTypeEnum
 */
export enum ModelTypeEnum {
    PROPHET = 'prophet'
}

/**
 * Represents an asset attribute feature used in model configuration.
 * Corresponds to Python class AssetAttributeFeature.
 */
export interface TargetFeature {
    /**
     * ID of the asset from OpenRemote.
     * Constraints: min_length=22, max_length=22
     */
    asset_id: string;
    /**
     * Name of the attribute of the asset.
     * Constraints: min_length=3
     */
    attribute_name: string;
    /**
     * ISO 8601 duration string, this duration period will be used for retrieving training data.
     * E.g. 'P6M' for data from the last 6 months.
     */
    training_data_period: string;
}

/**
 * Represents a regressor feature used in model configuration.
 */
export interface RegressorFeature {
    /**
     * ID of the asset from OpenRemote.
     * Constraints: min_length=22, max_length=22
     */
    asset_id: string;
    /**
     * Name of the attribute of the asset.
     * Constraints: min_length=3
     */
    attribute_name: string;
    /**
     * ISO 8601 duration string, this duration period will be used for retrieving training data.
     * E.g. 'P6M' for data from the last 6 months.
     */
    training_data_period: string;
}

/**
 * Base configuration common to all models.
 */
interface BaseModelConfig {
    /**
     * ID of the model configuration. If not provided, a random uuid v4 should be generated by the backend.
     */
    id?: string; // Optional as it has a default_factory
    /**
     * Realm where the assets and their datapoints are available.
     */
    realm: string;
    /**
     * Friendly name for the model configuration.
     */
    name: string;
    /**
     * Whether the model is enabled and will be scheduled for training and forecasting.
     * @default true
     */
    enabled?: boolean; // Optional as it has a default
    /**
     * Which model to use.
     */
    type: ModelTypeEnum;
    /**
     * The asset attribute to generate datapoints for.
     * There must be historical data available for training.
     */
    target: TargetFeature;
    /**
     * Forecast generation interval. Expects ISO 8601 duration strings.
     */
    forecast_interval: string;
    /**
     * Model training interval. Expects ISO 8601 duration strings.
     */
    training_interval: string;
    /**
     * Number of periods to forecast into the future.
     */
    forecast_periods: number;
    /**
     * The frequency of each forecasted datapoint. Expects a pandas frequency string.
     * E.g. '30min' or '1h'.
     * Generated forecast datapoints are rounded to the nearest frequency.
     * Example: 15:30 -> 16:00 -> 16:30 etc.
     */
    forecast_frequency: string;
}

/**
 * Seasonality modes for the Prophet model.
 */
export enum ProphetSeasonalityModeEnum {
    ADDITIVE = 'additive',
    MULTIPLICATIVE = 'multiplicative'
}

/**
 * Prophet specific model configuration.
 */
export interface ProphetModelConfig extends BaseModelConfig {
    /**
     * Discriminator field indicating the model type is Prophet.
     */
    type: ModelTypeEnum.PROPHET; // Use literal type for discriminator
    /**
     * List of asset attributes that will be used as regressors.
     * There must be historical data available for training.
     * There must also be future data available for forecasting.
     * @default null
     */
    regressors?: RegressorFeature[] | null; // Optional as it has a default
    /**
     * Include yearly seasonality in the model.
     * @default true
     */
    yearly_seasonality?: boolean; // Optional as it has a default
    /**
     * Include weekly seasonality in the model.
     * @default true
     */
    weekly_seasonality?: boolean; // Optional as it has a default
    /**
     * Include daily seasonality in the model.
     * @default true
     */
    daily_seasonality?: boolean; // Optional as it has a default
    /**
     * Seasonality mode of the model. Additive or multiplicative.
     * @default ProphetSeasonalityModeEnum.ADDITIVE
     */
    seasonality_mode?: ProphetSeasonalityModeEnum; // Optional as it has a default
    /**
     * Proportion of historical data used for detecting changepoints.
     * A higher value (e.g., 0.9-1.0) makes the model more responsive to recent trends.
     * Constraints: ge=0.0, le=1.0
     * @default 0.8
     */
    changepoint_range?: number; // Optional as it has a default
    /**
     * Controls trend flexibility at changepoints.
     * Lower values (e.g., 0.01) result in smoother trends,
     * while higher values (e.g., 0.5) allow more abrupt changes.
     * Constraints: ge=0.0, le=1.0
     * @default 0.05
     */
    changepoint_prior_scale?: number; // Optional as it has a default
}

/**
 * Represents a model configuration, which can be one of the specific model types.
 * This uses a discriminated union based on the 'type' field.
 */
export type ModelConfig = ProphetModelConfig;
