# Copyright 2025, OpenRemote Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from enum import Enum
from typing import Any

from pydantic import BaseModel


class BasicAttribute(BaseModel):
    """Minimal attribute of an asset."""

    name: str
    value: Any | None
    timestamp: int
    meta: dict[str, Any] | None = None


class BasicAsset(BaseModel):
    """Minimal asset of OpenRemote."""

    id: str
    name: str
    realm: str
    parentId: str | None = None
    attributes: dict[str, BasicAttribute]

    def get_attribute_value(self, attribute_name: str) -> Any | None:
        """Helper method to get an attribute value."""

        if attribute_name in self.attributes:
            return self.attributes[attribute_name].value
        return None


class AssetDatapointPeriod(BaseModel):
    """Datapoint period of an asset attribute."""

    assetId: str
    attributeName: str
    oldestTimestamp: int
    latestTimestamp: int


class AssetDatapoint(BaseModel):
    """Data point of an asset attribute.

    Args:
        x: The timestamp of the data point in milliseconds.
        y: The value of the data point.
    """

    x: int
    y: Any


class AssetDatapointQuery(BaseModel):
    """Request body for querying asset datapoints."""

    fromTimestamp: int
    toTimestamp: int
    fromTime: str = ""
    toTime: str = ""


class Realm(BaseModel):
    """Realm model."""

    name: str
    displayName: str


class ServiceStatus(str, Enum):
    """The status of a registered service.

    - AVAILABLE: The service is available and can be used
    - UNAVAILABLE: The service is unavailable
    """

    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class ServiceInfo(BaseModel):
    """Holds comprehensive details about a service.

    This object is used to register and deregister services.
    """

    serviceId: str
    """The unique identifier of the service, e.g. 'energy-service'"""

    instanceId: str | None = None
    """The unique instance identifier of the registered service,
    either generated by the service or provided by the user."""

    label: str
    """The label of the service, e.g. 'Energy Service'"""

    icon: str | None = None
    """The icon of the service, e.g. 'puzzle', must be part of the Material Design Icons set"""

    version: str | None = None
    """The version of the service, e.g. '1.0.0'"""

    homepageUrl: str
    """The URL of the service's homepage which provides the user interface,
    e.g. 'https://openremote.app/services/energy-service/ui'"""

    status: ServiceStatus
    """The status of the service, e.g. 'AVAILABLE'"""

    realm: str
    """The realm of the service, e.g. 'master'"""
