name: service-ml-forecast

services:
  service-ml-forecast:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ML_SERVICE_URL: ${ML_SERVICE_URL} # Will be embedded into the front-end, if not set it will make relative calls
    container_name: service-ml-forecast
    ports:
      - "8000:8000"
    environment:
      - ML_LOG_LEVEL=${ML_LOG_LEVEL:-INFO}
      - ML_ENVIRONMENT=${ML_ENVIRONMENT:-production}
      - ML_OR_URL=${ML_OR_URL:-http://host.docker.internal:8080}
      - ML_OR_KEYCLOAK_URL=${ML_OR_KEYCLOAK_URL:-http://host.docker.internal:8081}
      - ML_OR_SERVICE_USER=${ML_OR_SERVICE_USER:-serviceuser}
      - ML_OR_SERVICE_USER_SECRET=${ML_OR_SERVICE_USER_SECRET:-secret}
    volumes:
      - ../deployment/data/models:/app/deployment/data/models # Model storage
      - ../deployment/data/configs:/app/deployment/data/configs # Config storage
    restart: unless-stopped
    networks:
      - ml-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ml-network:
    driver: bridge
