name: Tests & Linting

on:
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4


    - name: GNU Make version
      run: make --version

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Create and activate Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: make install

    - name: Run lint check
      run: make lint

    - name: Run tests
      run: make test

      


