name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install uv package manager
      uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      with:
        version: "0.6.11"

    - name: Create and activate Python virtual environment
      run: |
        uv venv
        source .venv/bin/activate

    - name: Run linting and type checking
      run: uv run lint

    - name: Run tests with coverage
      run: uv run test-coverage

    - name: Run build steps
      run: uv run build
