name: Python Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: GNU Make version
      run: make --version

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Create and activate Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install all project dependencies
      run: make install

    - name: Run linting and type checking
      run: make lint

    - name: Run tests
      run: make test

    - name: Run build steps
      run: make build
