name: Release

on:
  # Manual trigger
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get pyproject.toml version details
        id: pyproject_version
        run: |
          echo "version=$(cat pyproject.toml | grep -E '^version = ' | cut -d'"' -f2)" >> $GITHUB_OUTPUT

      # When the 'github.token' is used events are not generated to prevent users from accidentally creating recursive workflow runs.
      # See: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # ------------------------------------------------------------------------------------------------
      # Creating a release will trigger the docker-image.yml workflow to build and push the docker image to Docker Hub with the tag of the release.
      - name: Create release
        run: |
          git tag $ML_FORECAST_VERSION
          git push origin tag $ML_FORECAST_VERSION
          gh release create $ML_FORECAST_VERSION --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          ML_FORECAST_VERSION: ${{ steps.pyproject_version.outputs.version }}
